import { EmailWrapper } from '@reactEmail/components';
import type { NextPage } from 'next';
import Head from 'next/head';

// import EmailWrapper from '@reactEmail/components';
const Home: NextPage = () => {
	return (
		<>
			<Head>
				<meta charSet='UTF-8' />
				<meta httpEquiv='X-UA-Compatible' content='IE=edge' />
				<meta name='viewport' content='width=device-width, initial-scale=1.0' />
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='./favicon.ico' />
				<title>Create Next App</title>
			</Head>

			<EmailWrapper></EmailWrapper>
		</>
	);
};

export default Home;
